apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: coit-frontend
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: coit-frontend
  endpoints:
  - port: web