apiVersion: apps/v1
kind: Deployment                                          # 1
metadata:
  name: coit-frontend
  labels:
    app: coit-frontend
spec:
  selector:
    matchLabels:
      app: coit-frontend
  replicas: 1                                             # 2
  minReadySeconds: 15
  strategy:
    type: RollingUpdate                                   # 3
    rollingUpdate: 
      maxUnavailable: 1                                   # 4
      maxSurge: 1                                         # 5
  template:
    metadata:
      labels:
        app: coit-frontend                                  # 6
    spec:
     # serviceAccountName: coit-frontend  
      containers:
        - image: chittiinfo/advk8s-coit-frontend:v1      
        #- image: coitlearning/coit-frontend:v4
          imagePullPolicy: IfNotPresent                         # 7
          name: coit-frontend
          # resources:
          #   requests:
          #     cpu: 100m
          #     memory: 250M
          #   limits:
          #     cpu: 150m
          #     memory: 450M
          ports:
            - containerPort: 80
          # env:
          #   - name: JAVA_APP_URL
          #     valueFrom:   
          #       configMapKeyRef:
          #         name: coit-frontend-config
          #         key: JAVA_URL
            
          
          
